#pragma kernel UpdateParticle

struct ParticleData {
	float3 pos;
	float4 color;
};

RWStructuredBuffer<ParticleData> ParticleBuffer;

float Time;

[numthreads(8, 8, 10)]
void UpdateParticle(uint3 gid : SV_GroupID, uint index : SV_GroupIndex)
{
	int pindex = gid.x * 640 + index;

	ParticleBuffer[pindex].pos = float3(pindex /640.0 + sin(Time), 5 * cos(pindex), 5 * sin(pindex));
	ParticleBuffer[pindex].color = float4((sin(Time) + 1) * 0.5, (cos(Time) + 1) * 0.5, abs(cos(Time) + sin(Time)), 1);
}